@startuml
left to right direction

actor User as u

package "Devices for Shopping" {
    rectangle "Personal Devices" {
        usecase "Smartphone" as UC1
        usecase "Tablet" as UC2
        usecase "SmartWatch" as UC3
        usecase "Laptop" as UC4
    }
    
    rectangle "Home Devices" {
        usecase "SmartSpeaker" as UC5
        usecase "SmartRefrigerator" as UC6
    }

    rectangle "Immersive Devices" {
        usecase "VRHeadset" as UC7
        usecase "ARSmartGlasses" as UC8
    }

    rectangle "Interactive Devices" {
        usecase "InteractiveDisplay" as UC9
        usecase "PointofSaleTerminal" as UC10
        usecase "SelfServiceKiosk" as UC11
    }

    rectangle "Payment Devices" {
        usecase "MobilePaymentTerminal" as UC12
        usecase "CashRegister" as UC13
    }
}

u --> "Personal Devices"
u --> "Home Devices"
u --> "Immersive Devices"
u --> "Interactive Devices"
u --> "Payment Devices"
@enduml
